baseurl = "https://pycastr.fm/"
languageCode = "es-mx"
title = "pycastR"
theme = "castanet-theme"
googleAnalytics = ""
themesdir = "."
paginate = "9"


[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "Sobre pycastR"
    identifier = "about"
    url = "/sobre-pycastR"

[[Menu.Main]]
    name = "Contáctanos"
    identifier = "contact"
    url = "/contactanos"

[[Menu.Main]]
    name = "Anfitriones"
    identifier = "hosts"
    url = "/host"

[[Menu.Main]]
    name = "Invitadxs"
    identifier = "guests"
    url = "/guest"

[[Menu.Main]]
    name = "Recursos"
    identifier = "resources"
    url = "#!"

[[Menu.Main]]
    name = "Libros 📚"
    identifier = "books"
    url = "/libros"
    parent = "resources"
[[Menu.Main]]
    name = "Podcasts 🎙️"
    identifier = "podcasts"
    url = "/podcasts"
    parent = "resources"

[params]
mainSections = ["episode"]
site_theme = "blue"
site_layout = "grid"
# site_layout = "row"
enable_jumbo = "true"
# enable_jumbo = "false"
# truncate = "100"
favicon = "https://cimarron.io/assets/images/logo.png"
copyright_notice = "Copyright 2020 [pycastR](https://www.pycastR.fm)"
itunes_subscribe = "http://itunes.apple.com/us/podcast/arrested-devops/id773888088?mt=2&uo=4&at=11lsCi"
android_subscribe = "http://subscribeonandroid.com/feeds.podtrac.com/VGAulpN7MY1U"
spotify_subscribe = "https://open.spotify.com/show/..."
google_play_subscribe = "https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ihj4yege3lfmp3vs5yoopgxijpi?t%3DArrested_DevOps"
stitcher_subscribe = "http://www.stitcher.com/podcast/arrested-devops-2/arrested-devops"
soundcloud_subscribe = "http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
pocketcasts_subscribe = "http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "Un podcast efímero de notícias y recursos para aprender del análisis y la visualización de datos. Presentado por [@tacosdedatos](https://twitter.com/tacosdedatos) y [@FerroRodolfo](https://twitter.com/ferrorodolfo)."
media_prefix = "https://media.blubrry.com/arresteddevops/content.blubrry.com/arresteddevops/"
disqusShortname = ""
  [params.feed]
    copyright = "Copyright 2016 Matt Stratton" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "The best podcast ever" #no markdown or HTML
    itunes_author = "Matt Stratton" #no markdown or HTML
    itunes_summary = "The HugoCast is the best podcast you've ever seen. You will learn everything you ever needed to know about podcasting from the most inspiring experts to ever show up on the whole internet." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Matt Stratton"
    itunes_owner_email = "matt.stratton@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "https://www.arresteddevops.com/img/ado-podcast-logo.png" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Software How-To"
    itunes_second_sub_category = "Tech News"
    language = "en-us"

  [params.podlove] # https://subscribe-button.podlove.org
    subscribe_title = ""              # fallback: site title from above
    subscribe_subtitle = ""           # fallback: ""
    subscribe_description = ""        # fallback: ""
    subscribe_cover = "img/logo.jpg"  # fallback: ""
    subscribe_color = "#585e6c"       # fallback: ""
    subscribe_size = "medium"         # options: small, medium, big
    subscribe_format = "rectangle"    # options: rectangle, square, cover
    subscribe_style = "filled"        # options: filled, outline, frameless
    subscribe_language = "de"         # options: nl (dutch), en (english), eo (esperanto), de (german), fi (finnish), fr (french), ja (french)
    subscribe_feed_type = "audio"     # options: audio, video
    subscribe_feed_format = "mp3"     # options: mp3, aac, ogg, opus

  [params.social]
    #github = "arresteddevops"
    #gitlab = "mattstratton"
    #facebook = "Arresteddevops"
    #facebook_admin = ["500557137","1234"] # This needs to be one or more page admins to get domain insights
    #twitter = "arresteddevops"
    #twitter_domain = "arresteddevops.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    #googleplus = "ArrestedDevOps"
    #pinterest = "nozzleio"
    #instagram = "nozzleio"
    #youtube = "arresteddevops"
    #linkedin = "mattstratton"
    #twitch = "mattstratton"

  [params.authors]
    [params.authors.Rodolfo]
      name	= "Rodolfo Ferro"
      thumbnail = "https://rodolfoferro.github.io/assets/images/profile.jpg"
      bio = "I am a science enthusiast, an AI practitioner experienced in the development of tech solutions using automation, artificial intelligence models, web services, computer vision, data extraction and data analysis. Helping startups and entrepreneurs with the power of AI. An eternal learner."
      [params.authors.Rodolfo.social]
        github = "rodolfoferro"
        #facebook = "matt.stratton"
        twitter = "ferrorodolfo"
        linkedin = "rodolfoferro"
        homepage = "https://www.rodolfoferro.xyz"
        #pinterest = "mattstratton"
        #instagram = "instagram"
        #youtube = "mattstratton"
        #twitch = "mattstratton"
    [params.authors.Sergio]
			name = "Sergio Sánchez"
			thumbnail = "https://soyserg.io/author/admin/avatar_hub20237ecfae90531d53ea56ecc56a3c7_1774668_250x250_fill_q75_box_center.jpg"
			bio = "My name is Sergio Sánchez Zavala and I’m originally from Tijuana, Baja California, México. I’m dedicated to making research transparent and reproducible. I’m a public policy wonk + data and tech nerd. I like making accessible and reproducible open-sourced tools and resources 🤓 <br> I’m also: <br> 🧑🏼‍🎨🧑🏼‍🏫 a facilitator in the newly formed Data Visualization Society.<br> 🌮📊 the creator of @tacosdedatos - tacosdedatos.com where I hope to build a place to learn data analysis and data visualization best practices, techniques, and knowledge in Spanish. <br> 🧑🏼‍🔬🎨 and a data visualization analyst at Alluma - a social enterprise in the social tech space."
				[params.authors.Trevor.social]
					twitter = "chekoswh"

    [params.links]
      [params.links.ado]
        name = "Arrested DevOps"
        url = "https://www.arresteddevops.com"
      [params.links.ffs]
        name = "Food Fight Show"
        url = "https://foodfightshow.org"
      [params.links.sdt]
        name = "Software Defined Talk"
        url = "https://cote.io/podcasts/sdt/"